import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '800'] });

export const metadata: Metadata = {
  title: 'Teleport - All abroad Education',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <link rel="icon" href="favicon.ico" sizes="any" />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
